clone template
searchspring/snapfu pull request #1
Opened 2020-09-20 21:43 UTC by codeallthethingz

2020-09-20 21:45 UTC, athos-machine commented
<b>Coverage Report</b><br>
```bash
PASS src/login.test.js
PASS src/init.test.js
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |   42.19 |    30.56 |   27.59 |   42.52 |                   
 init.js  |   24.36 |        5 |    9.52 |   24.68 | 23-130,135-166    
 login.js |      70 |     62.5 |      75 |      70 | 12-30             
----------|---------|----------|---------|---------|-------------------

Test Suites: 2 passed, 2 total
Tests:       7 passed, 7 total
Snapshots:   0 total
```

2020-09-21 17:19 UTC, zachbutton requested changes

2020-09-21 17:19 UTC, zachbutton commented on src/init.js
> +exports.createDir = function (dir) {
This function can be written more idiomatically as:

```js
exports.createDir = async dir => {
        let folderName = dir.substring(dir.lastIndexOf('/') + 1)
        let files = readdirSync(dir)
        if (files.length !== 0) {
            throw new Error('folder not empty, exiting');
        }

	return folderName;
};
```

2020-09-21 17:19 UTC, zachbutton commented on src/init.js
> +    let folderName = await exports
This function call string can be replaced with:

```js
let folderName = await exports.createDir(dir);
```

For error handling, you can wrap the entire init function in a try/catch:

```js
try {
    // init fn contents
} catch(err) {
    console.error(chalk.red(err));
    exit(1);
}
```

2020-09-21 17:19 UTC, zachbutton commented on src/init.js
> +        let templateUrl = `https://github.com/searchspring/snapfu-template-${answers.framework}`
Just a comment, I love this repo name scheme!

2020-09-21 17:19 UTC, zachbutton commented on src/init.js
> +        await exports
This can simply be written as:

```js
await exports.cloneAndCopyRepo(templateUrl, true);

console.log(`template initialized: ${chalk.blue(templateUrl)}`)
```

You don't need the catch either since a rejected promise will tthrow an error in an async function.

2020-09-21 17:19 UTC, zachbutton commented on src/init.js
> +    return new Promise(async (resolutionFunc, rejectionFunc) => {
Just a note: In another part of this review I left a note about simplifying a function that explicitly returned a new Promise. Counter to that, this function is a great example of promisifying a function via callback.

It would be a good idea to reject the promise somewhere, because otherwise you'll have a promise that never resolves if there's an error -- async functions using this function would await forever!

2020-09-21 17:19 UTC, zachbutton commented on src/init.js
> +                rejectionFunc(err)
And this is a great example of fully promisifying a function. The error passed into the callback will be the thrown error if this function is used in an async function, since it's rejecting the promise.

2020-09-21 23:48 UTC, athos-machine commented
<b>Coverage Report</b><br>
```bash
PASS src/login.test.js
PASS src/init.test.js
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |   43.55 |    28.95 |   33.33 |    43.9 |                   
 init.js  |   25.68 |     4.55 |    12.5 |   26.03 | 23-120,125-159    
 login.js |      70 |     62.5 |      75 |      70 | 12-30             
----------|---------|----------|---------|---------|-------------------

Test Suites: 2 passed, 2 total
Tests:       7 passed, 7 total
Snapshots:   0 total
```

2020-09-22 22:30 UTC, zachbutton requested changes

2020-09-22 22:30 UTC, zachbutton commented on src/init.js
> +var ncp = require('ncp').ncp
`const`

2020-09-22 22:30 UTC, zachbutton commented on src/init.js
> +    return new Promise((resolutionFunc, rejectionFunc) => {
I believe my last review proposed changes to this. Do those changes not work?

2020-09-22 22:30 UTC, zachbutton commented on package.json
>          "git-clone": "^0.1.0",
Let's consider adding these deps:

`npm i -D husky pretty-quick`

then add this package.json config:

```json
{
	"husky": {
		"hooks": {
			"pre-commit": "pretty-quick --staged"
		}
	}
}
```

Then, all staged changes will be formatted on commit.

2020-09-23 01:22 UTC, codeallthethingz commented on src/init.js
> +    return new Promise((resolutionFunc, rejectionFunc) => {
oh, this is the code formatter. It puts the parenthesis around it.

2020-09-23 01:32 UTC, codeallthethingz commented on package.json
>          "git-clone": "^0.1.0",
nice!

2020-09-23 01:32 UTC, merged